// FILE: controllers/recommendationController.js

// ── SAMPLE TRAVEL DATA ──
const destinations = [
  {
    id: 1,
    name: "Bali, Indonesia",
    country: "Indonesia",
    region: "Southeast Asia",
    travelType: "relaxing",
    budget: "moderate",
    description:
      "A tropical paradise famous for lush rice terraces, sacred temples, and stunning sunsets. Perfect for travelers seeking a balance of culture, nature, and beachside relaxation.",
    estimatedCost: "$1,200 – $2,000",
    bestSeason: "Apr – Oct",
    idealDuration: "7–10 days",
    travelVibe: "Relaxing & Cultural",
    insiderTip:
      "Visit Tegallalang Rice Terrace early in the morning before 8am to avoid crowds and get the best photos.",
    highlights: [
      "Ubud Rice Terraces",
      "Tegallalang Rice Fields",
      "Tanah Lot Temple",
      "Uluwatu Temple",
      "Kuta Beach",
      "Seminyak Beach",
      "Nusa Penida",
      "Mount Batur",
      "Monkey Forest",
      "Bali Swing",
      "Tirta Empul Temple",
      "Lovina Beach",
      "Gitgit Waterfall",
      "Campuhan Ridge Walk",
      "Jimbaran Bay",
      "Ulun Danu Temple",
      "Sekumpul Waterfall",
      "Amed Beach",
      "Sanur Beach",
      "Lempuyang Temple",
      "Sidemen Valley",
      "Kelingking Beach",
      "Angel’s Billabong",
      "Broken Beach",
      "Padang Padang Beach",
      "Green Bowl Beach",
      "Blue Lagoon Beach",
      "Bali Safari Park",
      "Handara Gate",
      "Bali Bird Park",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
  },
  {
    id: 2,
    name: "Santorini, Greece",
    country: "Greece",
    region: "Europe",
    travelType: "romantic",
    budget: "luxury",
    description:
      "Iconic whitewashed buildings perched on volcanic cliffs overlooking the deep blue Aegean Sea. A dream destination for couples seeking breathtaking sunsets and fine dining.",
    estimatedCost: "$3,500 – $6,000",
    bestSeason: "May – Sep",
    idealDuration: "5–7 days",
    travelVibe: "Romantic & Luxurious",
    insiderTip:
      "Stay in Oia for sunsets but explore Fira and Firostefani for better restaurant deals and fewer tourists.",
    highlights: [
      "Oia Sunset",
      "Fira Town",
      "Red Beach",
      "Perissa Beach",
      "Akrotiri Ruins",
      "Amoudi Bay",
      "Skaros Rock",
      "Volcano Tour",
      "Wine Tasting",
      "Pyrgos Village",
      "Imerovigli",
      "Kamari Beach",
      "Ancient Thera",
      "Sunset Cruise",
      "Caldera Views",
      "Megalochori",
      "Blue Dome Churches",
      "Black Sand Beach",
      "Thirassia Island",
      "Hot Springs",
      "Art Space Winery",
      "Profitis Ilias",
      "Vlychada Beach",
      "Cliff Jumping",
      "Castle Ruins",
      "Wine Museum",
      "Lighthouse",
      "Cycladic Gallery",
      "Cable Car Ride",
      "Oia Castle",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80",
  },
  {
    id: 3,
    name: "Kyoto, Japan",
    country: "Japan",
    region: "East Asia",
    travelType: "cultural",
    budget: "comfort",
    description:
      "The cultural heart of Japan, home to over 1,600 Buddhist temples, traditional tea houses, and world-famous bamboo groves. A timeless city where ancient tradition meets modern Japan.",
    estimatedCost: "$2,500 – $4,000",
    bestSeason: "Mar – May, Oct – Nov",
    idealDuration: "7 days",
    travelVibe: "Cultural & Serene",
    insiderTip:
      "Arrive at Fushimi Inari Shrine before 7am to walk the torii gates in complete solitude — it looks magical at dawn.",
    highlights: [
      "Fushimi Inari Shrine",
      "Arashiyama Bamboo Grove",
      "Golden Pavilion",
      "Gion District",
      "Kiyomizu Temple",
      "Nijo Castle",
      "Philosopher Path",
      "Ryoanji Garden",
      "Nishiki Market",
      "Maruyama Park",
      "Heian Shrine",
      "Toji Temple",
      "Imperial Palace",
      "Higashiyama",
      "Tea Ceremony",
      "Pontocho Alley",
      "Sagano Train",
      "Tenryuji Temple",
      "Kyoto Tower",
      "Silver Pavilion",
      "Daigoji Temple",
      "Kurama Temple",
      "Ohara Village",
      "Uji Town",
      "Samurai Museum",
      "Kimono Experience",
      "Kamo River",
      "Kyoto Aquarium",
      "Monkey Park",
      "Cherry Blossom Spots",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80",
  },
  {
    id: 4,
    name: "Patagonia, Argentina",
    country: "Argentina",
    region: "Americas",
    travelType: "adventure",
    budget: "comfort",
    description:
      "A vast, wild frontier of jagged mountain peaks, colossal glaciers, and pristine lakes stretching to the horizon. The ultimate destination for hikers and outdoor adventurers.",
    estimatedCost: "$2,800 – $4,500",
    bestSeason: "Nov – Mar",
    idealDuration: "10–14 days",
    travelVibe: "Adventure & Wild",
    insiderTip:
      "Book the W Trek in Torres del Paine at least 6 months in advance — campsites sell out extremely fast.",
    highlights: [
      "Perito Moreno Glacier",
      "El Calafate",
      "Torres del Paine National Park",
      "Mount Fitz Roy",
      "El Chaltén",
      "Los Glaciares National Park",
      "Ushuaia",
      "Beagle Channel",
      "Tierra del Fuego National Park",
      "Punta Tombo Penguin Reserve",
      "Lake Argentino",
      "Grey Glacier",
      "Cueva de las Manos",
      "Perito Moreno Walkways",
      "Estancia Cristina",
      "Río Gallegos",
      "Mount Torre",
      "Laguna de los Tres",
      "Fagnano Lake",
      "Magellanic Penguin Colony",
      "Southern Patagonian Ice Field",
      "Puerto Natales (Chile side access)",
      "Viedma Glacier",
      "Patagonia Steppe",
      "Patagonian Andes Drive",
      "Ona Ancient Sites",
      "Río Turbio",
      "Perito Moreno Village",
      "Southern Lights Viewing",
      "Windy Plains Trek",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
  },
  {
    id: 5,
    name: "Maldives",
    country: "Maldives",
    region: "South Asia",
    travelType: "luxury",
    budget: "ultra",
    description:
      "A necklace of coral islands with crystal-clear turquoise lagoons, powder-white sandbanks, and overwater bungalows. The pinnacle of tropical luxury travel on earth.",
    estimatedCost: "$5,000 – $12,000",
    bestSeason: "Nov – Apr",
    idealDuration: "5–7 days",
    travelVibe: "Ultra Luxury & Bliss",
    insiderTip:
      "Book a resort on the quieter northern atolls like Baa Atoll for better snorkeling and manta ray sightings.",
    highlights: [
      "Overwater Villas",
      "Baros Island",
      "Sun Island Resort",
      "Veligandu Island",
      "Banana Reef",
      "HP Reef",
      "Manta Point",
      "Hanifaru Bay",
      "Dhigurah Island",
      "Meeru Island",
      "Hulhumale Beach",
      "Vaadhoo Island Glowing Beach",
      "Biyadhoo Island",
      "Alimatha Island",
      "Fihalhohi Island",
      "Thulusdhoo Island",
      "Kuredu Island",
      "Reethi Beach",
      "Guraidhoo Island",
      "Nalaguraidhoo",
      "Fulhadhoo Island",
      "Kuda Huraa",
      "Olhuveli Beach",
      "Sunset Dolphin Cruise",
      "Underwater Restaurant Ithaa",
      "Coral Garden Diving",
      "Luxury Overwater Villas",
      "Snorkeling Coral Reefs",
      "Private Sandbanks",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80",
  },
  {
    id: 6,
    name: "Marrakech, Morocco",
    country: "Morocco",
    region: "Africa",
    travelType: "cultural",
    budget: "budget",
    description:
      "A sensory explosion of bustling souks, fragrant spice markets, intricate mosaics, and ancient medinas. One of the world's most vibrant and affordable cultural destinations.",
    estimatedCost: "$600 – $1,200",
    bestSeason: "Mar – May, Sep – Nov",
    idealDuration: "4–6 days",
    travelVibe: "Cultural & Vibrant",
    insiderTip:
      "Always agree on a price before getting into a petit taxi and explore the souks with a local guide on day one.",
    highlights: [
      "Jemaa el-Fnaa Square",
      "Majorelle Garden",
      "Koutoubia Mosque",
      "Bahia Palace",
      "Saadian Tombs",
      "Medina of Marrakech",
      "Souks of Marrakech",
      "El Badi Palace",
      "Menara Gardens",
      "Atlas Mountains Day Trip",
      "Ouzoud Waterfalls",
      "Agafay Desert",
      "Ait Ben Haddou",
      "Essaouira Coast",
      "Chefchaouen Blue City",
      "Rabat Medina",
      "Casablanca Hassan II Mosque",
      "Fes Old Medina",
      "Tanneries of Fes",
      "Volubilis Ruins",
      "Ifrane Alpine Town",
      "Zagora Desert",
      "Merzouga Dunes",
      "Camel Trek Sahara",
      "Kasbah Telouet",
      "Dades Valley",
      "Todgha Gorge",
      "Skoura Oasis",
      "Rose Valley",
      "Atlas Film Studios",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80",
  },
  {
    id: 7,
    name: "Amalfi Coast, Italy",
    country: "Italy",
    region: "Europe",
    travelType: "romantic",
    budget: "luxury",
    description:
      "Dramatic clifftop villages tumbling down to a glittering blue sea, with lemon groves, fresh seafood, and timeless Italian charm at every turn. One of Europe's most breathtaking coastlines.",
    estimatedCost: "$3,000 – $5,500",
    bestSeason: "May – Oct",
    idealDuration: "5–8 days",
    travelVibe: "Romantic & Scenic",
    insiderTip:
      "Avoid driving the coastal road in July and August — take the ferry between Positano, Amalfi, and Ravello instead.",
    highlights: [
      "Positano",
      "Amalfi Town",
      "Ravello",
      "Capri Island",
      "Blue Grotto",
      "Path of the Gods",
      "Sorrento",
      "Praiano",
      "Atrani Village",
      "Fiordo di Furore",
      "Duomo di Amalfi",
      "Villa Rufolo",
      "Villa Cimbrone",
      "Naples Historic Center",
      "Pompeii Ruins",
      "Mount Vesuvius",
      "Marina Grande Capri",
      "Faraglioni Rocks",
      "Anacapri",
      "Lemon Groves Amalfi",
      "Spiaggia Grande",
      "Marina Piccola",
      "Sunset Viewpoints",
      "La Dolce Vita Coast Drive",
      "Church of Santa Maria",
      "Cliffside Cafes",
      "Mediterranean Beaches",
      "Boat Tours Capri",
      "Ligurian Sea Views",
      "Hidden Coves Amalfi",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1534445867742-43195f401b6c?w=800&q=80",
  },
  {
    id: 8,
    name: "Queenstown, New Zealand",
    country: "New Zealand",
    region: "Oceania",
    travelType: "adventure",
    budget: "comfort",
    description:
      "The adventure capital of the world, sitting on the shores of Lake Wakatipu surrounded by the Remarkables mountain range. Bungee jumping, skydiving, skiing, and stunning landscapes all in one place.",
    estimatedCost: "$2,500 – $4,000",
    bestSeason: "Dec – Feb, Jun – Aug",
    idealDuration: "5–7 days",
    travelVibe: "Adventure & Thrilling",
    insiderTip:
      "The Fergburger queue is always long but worth every minute — go after 10pm when the crowds thin out.",
    highlights: [
      "Lake Wakatipu",
      "Remarkables Mountain Range",
      "Milford Sound",
      "Fiordland National Park",
      "Skyline Gondola",
      "Bungee Jump Kawarau Bridge",
      "Shotover Jet",
      "Arrowtown",
      "Wanaka Lake",
      "Hooker Valley Track",
      "Franz Josef Glacier",
      "Fox Glacier",
      "Aoraki Mount Cook",
      "Lake Tekapo",
      "Church of Good Shepherd",
      "Coronet Peak",
      "Queenstown Gardens",
      "Ben Lomond Track",
      "Skippers Canyon",
      "Glenorchy",
      "Routeburn Track",
      "Milford Track",
      "Doubtful Sound",
      "Lake Hawea",
      "Paradise Valley",
      "Nzone Skydive",
      "Earnslaw Cruise",
      "Onsen Hot Pools",
      "Kawarau River",
      "Southern Alps Scenic Drive",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800&q=80",
  },
  {
    id: 9,
    name: "Dubai, UAE",
    country: "United Arab Emirates",
    region: "Middle East",
    travelType: "luxury",
    budget: "luxury",
    description:
      "A futuristic city rising from the desert with the world's tallest buildings, most extravagant hotels, and largest shopping malls. Dubai blends Arabian heritage with jaw-dropping modern ambition.",
    estimatedCost: "$3,500 – $8,000",
    bestSeason: "Nov – Mar",
    idealDuration: "4–6 days",
    travelVibe: "Luxury & Futuristic",
    insiderTip:
      "Visit the Burj Khalifa at sunset and stay for the Dubai Fountain show — book observation deck tickets online to skip the long queue.",
    highlights: [
      "Burj Khalifa",
      "Dubai Mall",
      "Palm Jumeirah",
      "Dubai Marina",
      "Desert Safari",
      "Burj Al Arab",
      "Jumeirah Beach",
      "Global Village",
      "Dubai Frame",
      "Museum of Future",
      "Dubai Creek",
      "Gold Souk",
      "Miracle Garden",
      "IMG Worlds",
      "Atlantis Waterpark",
      "Kite Beach",
      "Bluewaters Island",
      "Ain Dubai",
      "La Mer Beach",
      "Al Fahidi District",
      "Dubai Opera",
      "Ski Dubai",
      "City Walk",
      "Boxpark",
      "Hatta Mountains",
      "Love Lake",
      "Dragon Mart",
      "Zabeel Park",
      "Sunset Beach",
      "JBR Walk",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80",
  },
  {
    id: 10,
    name: "Banff, Canada",
    country: "Canada",
    region: "Americas",
    travelType: "nature",
    budget: "comfort",
    description:
      "Turquoise glacier-fed lakes, snow-capped Rocky Mountain peaks, and abundant wildlife make Banff one of the most spectacular national parks on earth. A paradise for hikers and nature lovers.",
    estimatedCost: "$2,000 – $3,500",
    bestSeason: "Jun – Sep, Dec – Feb",
    idealDuration: "5–7 days",
    travelVibe: "Nature & Majestic",
    insiderTip:
      "Lake Louise and Moraine Lake get extremely crowded — arrive before 7am or take the Parks Canada shuttle to secure your spot.",
    highlights: [
      "Lake Louise",
      "Moraine Lake",
      "Banff Town",
      "Icefields Parkway",
      "Columbia Icefield",
      "Peyto Lake",
      "Johnston Canyon",
      "Sulphur Mountain",
      "Banff Gondola",
      "Bow Falls",
      "Lake Minnewanka",
      "Emerald Lake",
      "Yoho National Park",
      "Athabasca Falls",
      "Tunnel Mountain",
      "Castle Mountain",
      "Sunshine Village",
      "Lake Agnes Tea House",
      "Vermilion Lakes",
      "Bow Valley Parkway",
      "Wildlife spotting",
      "Glacier Skywalk",
      "Mistaya Canyon",
      "Lake O’Hara",
      "Sherbrooke Lake",
      "Mount Rundle",
      "Cave and Basin",
      "Banff Hot Springs",
      "Rocky Mountain Views",
      "Snow Peak Trails",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=800&q=80",
  },
  {
    id: 11,
    name: "Lahore, Pakistan",
    country: "Pakistan",
    region: "South Asia",
    travelType: "cultural",
    budget: "budget",
    description:
      "The heart of Pakistani culture, packed with Mughal architecture, vibrant bazaars, and some of the world's best street food. Lahore is a city of poetry, music, and incredible history.",
    estimatedCost: "$300 – $700",
    bestSeason: "Oct – Mar",
    idealDuration: "3–5 days",
    travelVibe: "Cultural & Vibrant",
    insiderTip:
      "Visit the Walled City at dusk and end your evening with a traditional meal at Phajja Siri Paye on Gawalmandi Food Street.",
    highlights: [
      "Badshahi Mosque",
      "Lahore Fort",
      "Minar e Pakistan",
      "Shalimar Gardens",
      "Wagah Border",
      "Food Street",
      "Anarkali Bazaar",
      "Liberty Market",
      "Emporium Mall",
      "Packages Mall",
      "Model Town Park",
      "Jilani Park",
      "Race Course Park",
      "Gaddafi Stadium",
      "Data Darbar",
      "Tomb of Jahangir",
      "Ichra Bazaar",
      "MM Alam Road",
      "Fort Road",
      "Heera Mandi",
      "Punjab Museum",
      "Lahore Zoo",
      "Safari Park",
      "Bahria Eiffel Tower",
      "Lake City",
      "Canal Road",
      "Chaman Ice Cream",
      "Butt Karahi",
      "Cafe Aylanto",
      "Cuckoo's Den",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1603491656337-3b491147917c?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bGFob3JlfGVufDB8fDB8fHww",
  },
  {
    id: 12,
    name: "Cape Town, South Africa",
    country: "South Africa",
    region: "Africa",
    travelType: "adventure",
    budget: "moderate",
    description:
      "A breathtaking city between mountains and ocean, with world-class beaches, incredible food and wine, and the iconic Table Mountain looming over it all. One of Africa's most beautiful cities.",
    estimatedCost: "$1,500 – $2,800",
    bestSeason: "Oct – Apr",
    idealDuration: "7–10 days",
    travelVibe: "Adventure & Scenic",
    insiderTip:
      "Take the cable car up Table Mountain in the morning — clouds roll in by afternoon and can block the view entirely.",
    highlights: [
      "Table Mountain",
      "Cape of Good Hope",
      "Boulders Beach Penguins",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80",
  },
  {
    id: 13,
    name: "Barcelona, Spain",
    country: "Spain",
    region: "Europe",
    travelType: "cultural",
    budget: "moderate",
    description:
      "A city alive with Gaudí's surreal architecture, golden beaches, world-class tapas, and a nightlife scene that never seems to end. Barcelona effortlessly blends art, food, and Mediterranean sunshine.",
    estimatedCost: "$1,500 – $3,000",
    bestSeason: "Apr – Jun, Sep – Nov",
    idealDuration: "5–7 days",
    travelVibe: "Cultural & Lively",
    insiderTip:
      "Book Sagrada Família tickets at least 2 months in advance and go for the first morning slot to experience it without crowds.",
    highlights: ["Sagrada Família", "Park Güell", "La Boqueria Market"],
    imageUrl:
      "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=800&q=80",
  },
  {
    id: 14,
    name: "Phuket, Thailand",
    country: "Thailand",
    region: "Southeast Asia",
    travelType: "relaxing",
    budget: "budget",
    description:
      "Thailand's largest island with powder-white beaches, crystal-clear waters, affordable luxury resorts, and some of the best street food in the world. Perfect for budget travelers who still want paradise.",
    estimatedCost: "$700 – $1,500",
    bestSeason: "Nov – Apr",
    idealDuration: "7–10 days",
    travelVibe: "Relaxing & Affordable",
    insiderTip:
      "Skip Patong Beach if you want peace and quiet — head to Kata Noi or Nai Harn Beach for a much more relaxed atmosphere.",
    highlights: ["Phi Phi Islands", "Big Buddha", "Old Phuket Town"],
    imageUrl:
      "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=800&q=80",
  },
  {
    id: 15,
    name: "Istanbul, Turkey",
    country: "Turkey",
    region: "Europe",
    travelType: "cultural",
    budget: "moderate",
    description:
      "The only city in the world that straddles two continents, Istanbul is a dazzling mix of Byzantine churches, Ottoman mosques, grand bazaars, and a buzzing modern food scene along the Bosphorus.",
    estimatedCost: "$1,000 – $2,200",
    bestSeason: "Apr – Jun, Sep – Nov",
    idealDuration: "5–7 days",
    travelVibe: "Cultural & Historic",
    insiderTip:
      "Cross the Bosphorus on a public ferry for just a few lira — it gives you the most stunning views of the city skyline that no tour bus can match.",
    highlights: ["Hagia Sophia", "Grand Bazaar", "Bosphorus Cruise"],
    imageUrl:
      "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80",
  },
  {
    id: 16,
    name: "Paris, France",
    country: "France",
    region: "Europe",
    travelType: "romantic",
    budget: "luxury",
    description:
      "The city of love and light, where world-class art, iconic architecture, and exquisite cuisine come together on the banks of the Seine. Paris is a timeless dream for every traveler.",
    estimatedCost: "$3,000 – $5,500",
    bestSeason: "Apr – Jun, Sep – Nov",
    idealDuration: "5–7 days",
    travelVibe: "Romantic & Elegant",
    insiderTip:
      "Skip the Eiffel Tower queue — walk to Trocadéro at sunrise for the best view with almost no crowds.",
    highlights: ["Eiffel Tower", "Louvre Museum", "Montmartre & Sacré-Cœur"],
    imageUrl:
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80",
  },
  {
    id: 17,
    name: "New York City, USA",
    country: "United States",
    region: "Americas",
    travelType: "cultural",
    budget: "comfort",
    description:
      "The city that never sleeps — an electrifying mix of world-class museums, iconic skylines, diverse food scenes, and neighborhoods each with their own unique personality.",
    estimatedCost: "$2,500 – $5,000",
    bestSeason: "Apr – Jun, Sep – Nov",
    idealDuration: "5–7 days",
    travelVibe: "Urban & Vibrant",
    insiderTip:
      "Walk the Brooklyn Bridge at 7am on a weekday — you will have it almost entirely to yourself with perfect Manhattan views.",
    highlights: ["Central Park", "Times Square", "Brooklyn Bridge"],
    imageUrl:
      "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80",
  },
  {
    id: 18,
    name: "Rio de Janeiro, Brazil",
    country: "Brazil",
    region: "Americas",
    travelType: "adventure",
    budget: "moderate",
    description:
      "A breathtaking city sandwiched between rainforest mountains and golden beaches, famous for its carnival spirit, samba rhythms, and the iconic Christ the Redeemer statue.",
    estimatedCost: "$1,500 – $3,000",
    bestSeason: "Dec – Mar",
    idealDuration: "5–7 days",
    travelVibe: "Vibrant & Festive",
    insiderTip:
      "Take the Santa Teresa tram and walk the neighborhood streets for the most authentic local experience away from tourist crowds.",
    highlights: [
      "Christ the Redeemer",
      "Copacabana Beach",
      "Sugarloaf Mountain",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&q=80",
  },
  {
    id: 19,
    name: "Prague, Czech Republic",
    country: "Czech Republic",
    region: "Europe",
    travelType: "cultural",
    budget: "budget",
    description:
      "A fairy-tale city of gothic spires, cobblestone streets, medieval castles, and centuries-old beer halls. Prague is one of Europe's most beautiful and affordable capitals.",
    estimatedCost: "$800 – $1,800",
    bestSeason: "Mar – May, Sep – Nov",
    idealDuration: "3–5 days",
    travelVibe: "Historic & Magical",
    insiderTip:
      "Cross Charles Bridge at 6am before the crowds arrive — the mist over the Vltava River makes it look like a painting.",
    highlights: ["Prague Castle", "Charles Bridge", "Old Town Square"],
    imageUrl:
      "https://images.unsplash.com/photo-1541849546-216549ae216d?w=800&q=80",
  },
  {
    id: 20,
    name: "Petra, Jordan",
    country: "Jordan",
    region: "Middle East",
    travelType: "cultural",
    budget: "moderate",
    description:
      "The Rose City carved entirely into pink sandstone cliffs by the Nabataeans over 2,000 years ago. Petra is one of the world's most awe-inspiring archaeological wonders.",
    estimatedCost: "$1,200 – $2,500",
    bestSeason: "Mar – May, Sep – Nov",
    idealDuration: "2–3 days",
    travelVibe: "Historic & Mystical",
    insiderTip:
      "Attend Petra by Night on Monday, Wednesday, or Thursday — the Treasury lit by 1,500 candles is an unforgettable experience.",
    highlights: ["The Treasury", "The Siq Canyon", "Monastery Al-Deir"],
    imageUrl:
      "https://images.unsplash.com/photo-1548786811-dd6e453ccca7?w=800&q=80",
  },
  {
    id: 21,
    name: "Serengeti, Tanzania",
    country: "Tanzania",
    region: "Africa",
    travelType: "nature",
    budget: "luxury",
    description:
      "Witness the greatest wildlife spectacle on earth — millions of wildebeest and zebra crossing vast golden plains while lions, leopards, and elephants roam freely around you.",
    estimatedCost: "$4,000 – $9,000",
    bestSeason: "Jun – Oct",
    idealDuration: "7–10 days",
    travelVibe: "Wild & Majestic",
    insiderTip:
      "Book a hot air balloon safari at dawn over the Serengeti — watching the migration from above at sunrise is truly once-in-a-lifetime.",
    highlights: [
      "Great Migration",
      "Big Five Game Drives",
      "Ngorongoro Crater",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800&q=80",
  },
  {
    id: 22,
    name: "Reykjavik, Iceland",
    country: "Iceland",
    region: "Europe",
    travelType: "adventure",
    budget: "luxury",
    description:
      "The land of fire and ice where you can chase the Northern Lights, soak in geothermal hot springs, hike active volcanoes, and see glaciers all in a single trip.",
    estimatedCost: "$3,500 – $7,000",
    bestSeason: "Jun – Aug, Nov – Feb",
    idealDuration: "7–10 days",
    travelVibe: "Adventure & Magical",
    insiderTip:
      "Download the Vedur app for real-time Northern Lights forecasts — chase them away from city lights toward Þingvellir National Park.",
    highlights: ["Northern Lights", "Blue Lagoon", "Golden Circle"],
    imageUrl:
      "https://images.unsplash.com/photo-1531168556467-80aace0d0144?w=800&q=80",
  },
  {
    id: 23,
    name: "Ha Long Bay, Vietnam",
    country: "Vietnam",
    region: "Southeast Asia",
    travelType: "nature",
    budget: "budget",
    description:
      "Over 1,600 limestone karst islands rising dramatically from emerald-green waters, dotted with hidden caves, floating fishing villages, and pristine beaches.",
    estimatedCost: "$600 – $1,400",
    bestSeason: "Oct – Apr",
    idealDuration: "2–3 days",
    travelVibe: "Nature & Serene",
    insiderTip:
      "Book a 2-night overnight cruise rather than a day trip — you get to explore the bay after all day tourists have left and it is magical.",
    highlights: [
      "Overnight Cruise",
      "Sung Sot Cave",
      "Kayaking Through Karsts",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80",
  },
  {
    id: 24,
    name: "Machu Picchu, Peru",
    country: "Peru",
    region: "Americas",
    travelType: "adventure",
    budget: "moderate",
    description:
      "The lost Incan citadel perched high in the Andes cloud forest — one of the most spectacular and mysterious ancient sites on earth, surrounded by mist-covered mountain peaks.",
    estimatedCost: "$1,500 – $3,000",
    bestSeason: "May – Sep",
    idealDuration: "5–7 days",
    travelVibe: "Adventure & Historic",
    insiderTip:
      "Take the first bus up at 5:30am to arrive before the crowds and catch the sunrise mist burning off the ruins — it is absolutely magical.",
    highlights: ["Incan Citadel", "Inca Trail Hike", "Sun Gate Viewpoint"],
    imageUrl:
      "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80",
  },
  {
    id: 25,
    name: "Amsterdam, Netherlands",
    country: "Netherlands",
    region: "Europe",
    travelType: "cultural",
    budget: "moderate",
    description:
      "A city of canals, cycling culture, world-class museums, and vibrant nightlife. Amsterdam's unique blend of history, art, and liberal spirit makes it endlessly charming.",
    estimatedCost: "$1,500 – $3,000",
    bestSeason: "Apr – May, Sep – Oct",
    idealDuration: "3–5 days",
    travelVibe: "Cultural & Charming",
    insiderTip:
      "Rent a bike on day one — it is the fastest and most authentic way to explore the city and locals will immediately respect you for it.",
    highlights: ["Anne Frank House", "Van Gogh Museum", "Canal Ring Cycling"],
    imageUrl:
      "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80",
  },
  {
    id: 26,
    name: "Mecca, Saudi Arabia",
    country: "Saudi Arabia",
    region: "Middle East",
    travelType: "spiritual",
    budget: "moderate",
    description:
      "The holiest city in Islam and the destination of the Hajj pilgrimage — a profound spiritual journey to the Masjid al-Haram, the Grand Mosque, and the sacred Kaaba.",
    estimatedCost: "$2,000 – $5,000",
    bestSeason: "Nov – Feb",
    idealDuration: "5–14 days",
    travelVibe: "Spiritual & Sacred",
    insiderTip:
      "Perform Tawaf (circling the Kaaba) in the early hours of the morning between 2am and 5am when the crowds are at their lightest.",
    highlights: ["Masjid al-Haram", "Mount Arafat", "Zamzam Well"],
    imageUrl:
      "https://images.unsplash.com/photo-1513072064285-240f87fa81e8?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8bWFra2FofGVufDB8fDB8fHwws",
  },
  {
    id: 27,
    name: "Hunza Valley, Pakistan",
    country: "Pakistan",
    region: "South Asia",
    travelType: "nature",
    budget: "budget",
    description:
      "A breathtaking valley nestled among some of the world's highest peaks including Rakaposhi and Ultar Sar, with ancient forts, crystal rivers, and some of the most hospitable people on earth.",
    estimatedCost: "$400 – $900",
    bestSeason: "Apr – Oct",
    idealDuration: "4–7 days",
    travelVibe: "Nature & Serene",
    insiderTip:
      "Visit in April during cherry blossom season — the pink and white blossoms against snow-capped 7,000m peaks is one of the most beautiful sights in all of Asia.",
    highlights: ["Baltit Fort", "Attabad Lake", "Rakaposhi Base Camp Trek"],
    imageUrl:
      "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=800&q=80",
  },
  {
    id: 28,
    name: "Swiss Alps, Switzerland",
    country: "Switzerland",
    region: "Europe",
    travelType: "adventure",
    budget: "ultra",
    description:
      "Europe's most iconic mountain playground with pristine ski slopes, dramatic glaciers, charming alpine villages, and the legendary Matterhorn rising above it all.",
    estimatedCost: "$5,000 – $12,000",
    bestSeason: "Dec – Mar, Jun – Sep",
    idealDuration: "7–10 days",
    travelVibe: "Adventure & Luxury",
    insiderTip:
      "Take the Glacier Express train from Zermatt to St. Moritz — it is one of the world's most scenic rail journeys and worth every franc.",
    highlights: ["Matterhorn", "Jungfraujoch", "Glacier Express Train"],
    imageUrl:
      "https://images.unsplash.com/photo-1527095655060-4026c4af2b25?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fHN3aXR6ZXJsYW5kfGVufDB8fDB8fHww",
  },
  {
    id: 29,
    name: "Angkor Wat, Cambodia",
    country: "Cambodia",
    region: "Southeast Asia",
    travelType: "cultural",
    budget: "budget",
    description:
      "The largest religious monument on earth — a vast 12th-century Khmer temple complex rising from the jungle, with intricate stone carvings, moats, and towers that take your breath away.",
    estimatedCost: "$600 – $1,200",
    bestSeason: "Nov – Mar",
    idealDuration: "3–4 days",
    travelVibe: "Historic & Awe-Inspiring",
    insiderTip:
      "Watch sunrise at Angkor Wat from the reflecting pool — arrive by 5am for the best spot, then explore Ta Prohm jungle temple before 9am while it is quiet.",
    highlights: [
      "Angkor Wat Sunrise",
      "Ta Prohm Jungle Temple",
      "Bayon Temple Faces",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&q=80",
  },
  {
    id: 30,
    name: "Tokyo, Japan",
    country: "Japan",
    region: "East Asia",
    travelType: "cultural",
    budget: "comfort",
    description:
      "A neon-lit megacity where ancient temples sit beside futuristic skyscrapers, world-class sushi restaurants, and the most efficient subway system on earth. Tokyo is endlessly fascinating.",
    estimatedCost: "$2,500 – $4,500",
    bestSeason: "Mar – May, Sep – Nov",
    idealDuration: "7–10 days",
    travelVibe: "Urban & Futuristic",
    insiderTip:
      "Get a Suica card on arrival — it works on every train, subway, and even convenience stores across the entire city.",
    highlights: ["Shibuya Crossing", "Senso-ji Temple", "Tsukiji Fish Market"],
    imageUrl:
      "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
  },
  {
    id: 31,
    name: "Rome, Italy",
    country: "Italy",
    region: "Europe",
    travelType: "cultural",
    budget: "moderate",
    description:
      "The Eternal City where every cobblestone street leads to another masterpiece — the Colosseum, Vatican, Trevi Fountain, and some of the world's greatest pasta dishes.",
    estimatedCost: "$1,500 – $3,000",
    bestSeason: "Apr – Jun, Sep – Oct",
    idealDuration: "4–6 days",
    travelVibe: "Historic & Romantic",
    insiderTip:
      "Visit the Colosseum at opening time 9am sharp — queues grow massively by 11am. Book tickets online 2 days before.",
    highlights: ["Colosseum", "Vatican Museums", "Trevi Fountain"],
    imageUrl:
      "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80",
  },
  {
    id: 32,
    name: "Lisbon, Portugal",
    country: "Portugal",
    region: "Europe",
    travelType: "cultural",
    budget: "budget",
    description:
      "A sun-drenched city of yellow trams, fado music, pastel-colored buildings, and some of Europe's most affordable and delicious food. Lisbon is charming, hilly, and completely unique.",
    estimatedCost: "$900 – $2,000",
    bestSeason: "Mar – May, Sep – Oct",
    idealDuration: "4–5 days",
    travelVibe: "Charming & Affordable",
    insiderTip:
      "Ride Tram 28 in the early morning before 8am — it passes through the most scenic neighborhoods without the tourist crowds.",
    highlights: ["Alfama District", "Belém Tower", "Time Out Market"],
    imageUrl:
      "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80",
  },
  {
    id: 33,
    name: "Cappadocia, Turkey",
    country: "Turkey",
    region: "Middle East",
    travelType: "adventure",
    budget: "moderate",
    description:
      "A surreal landscape of fairy chimneys, cave hotels, underground cities, and hundreds of hot air balloons floating above rose-colored valleys at sunrise. Cappadocia is unlike anywhere else on earth.",
    estimatedCost: "$1,200 – $2,500",
    bestSeason: "Apr – Jun, Sep – Nov",
    idealDuration: "3–4 days",
    travelVibe: "Magical & Unique",
    insiderTip:
      "Book your hot air balloon ride 2–3 months in advance — they sell out fast and cost around $180–$250 per person.",
    highlights: [
      "Hot Air Balloon Ride",
      "Göreme Open Air Museum",
      "Underground Cities",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1695415683093-ae5f213ea898?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2FwYWRvY2lhfGVufDB8fDB8fHww",
  },
  {
    id: 34,
    name: "Zanzibar, Tanzania",
    country: "Tanzania",
    region: "Africa",
    travelType: "relaxing",
    budget: "moderate",
    description:
      "A spice island paradise off the coast of East Africa with powdery white beaches, turquoise waters, a UNESCO-listed Stone Town, and a rich blend of African, Arab, and Indian cultures.",
    estimatedCost: "$1,200 – $2,800",
    bestSeason: "Jun – Oct",
    idealDuration: "5–7 days",
    travelVibe: "Beach & Cultural",
    insiderTip:
      "Stay in Stone Town for your first night to explore the labyrinth alleys at night — then head to the north beaches for the rest of your trip.",
    highlights: ["Nungwi Beach", "Stone Town", "Spice Farm Tour"],
    imageUrl:
      "https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?w=800&q=80",
  },
  {
    id: 35,
    name: "Bora Bora, French Polynesia",
    country: "French Polynesia",
    region: "Oceania",
    travelType: "luxury",
    budget: "ultra",
    description:
      "The jewel of the South Pacific — a volcanic island surrounded by a turquoise lagoon of impossible beauty, with luxury overwater bungalows, colorful coral reefs, and Mount Otemanu towering above.",
    estimatedCost: "$6,000 – $15,000",
    bestSeason: "May – Oct",
    idealDuration: "5–7 days",
    travelVibe: "Ultra Luxury & Paradise",
    insiderTip:
      "Book a bungalow on the western side of the lagoon for direct sunset views over Mount Otemanu every evening.",
    highlights: ["Overwater Bungalows", "Lagoon Snorkeling", "Mount Otemanu"],
    imageUrl:
      "https://images.unsplash.com/photo-1589197331516-4d84b72ebde3?w=800&q=80",
  },
  {
    id: 36,
    name: "Havana, Cuba",
    country: "Cuba",
    region: "Americas",
    travelType: "cultural",
    budget: "budget",
    description:
      "A city frozen beautifully in time — classic 1950s American cars cruising colorful streets, salsa music spilling from doorways, crumbling colonial architecture, and the warmest people you will ever meet.",
    estimatedCost: "$700 – $1,500",
    bestSeason: "Nov – Apr",
    idealDuration: "4–6 days",
    travelVibe: "Vibrant & Nostalgic",
    insiderTip:
      "Exchange your currency at CADECA offices rather than hotels — you will get a significantly better rate every time.",
    highlights: ["Old Havana", "Malecón Waterfront", "Classic Car Tour"],
    imageUrl:
      "https://images.unsplash.com/photo-1500759285222-a95626b934cb?w=800&q=80",
  },
  {
    id: 37,
    name: "Bhutan",
    country: "Bhutan",
    region: "South Asia",
    travelType: "spiritual",
    budget: "luxury",
    description:
      "The last Himalayan Buddhist kingdom, measuring happiness over GDP. Dramatic monasteries cling to cliffsides, prayer flags flutter in mountain winds, and pristine forests cover 70% of the country.",
    estimatedCost: "$3,000 – $6,000",
    bestSeason: "Mar – May, Sep – Nov",
    idealDuration: "7–10 days",
    travelVibe: "Spiritual & Serene",
    insiderTip:
      "The daily tourist fee of $200 includes accommodation, meals, and guide — it is actually great value once you understand what is included.",
    highlights: ["Tiger's Nest Monastery", "Punakha Dzong", "Dochula Pass"],
    imageUrl:
      "https://plus.unsplash.com/premium_photo-1661952578770-79010299a9f9?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Ymh1dGFufGVufDB8fDB8fHww",
  },
  {
    id: 38,
    name: "Nairobi, Kenya",
    country: "Kenya",
    region: "Africa",
    travelType: "adventure",
    budget: "moderate",
    description:
      "Africa's most cosmopolitan city and the gateway to the world's greatest wildlife safaris. Watch giraffes roam freely near the city, then head to Masai Mara for the most breathtaking game drives on earth.",
    estimatedCost: "$1,500 – $3,500",
    bestSeason: "Jul – Oct",
    idealDuration: "7–10 days",
    travelVibe: "Wild & Urban",
    insiderTip:
      "Visit Giraffe Centre at opening time 9am — you can hand-feed Rothschild giraffes and get amazing photos before the school groups arrive.",
    highlights: [
      "Masai Mara Safari",
      "Giraffe Centre",
      "Nairobi National Park",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&q=80",
  },
  {
    id: 39,
    name: "Vienna, Austria",
    country: "Austria",
    region: "Europe",
    travelType: "cultural",
    budget: "comfort",
    description:
      "The imperial capital of Europe — grand palaces, world-class opera, the finest coffee houses, Mozart's birthplace, and museums that contain some of the most important art in human history.",
    estimatedCost: "$2,000 – $3,500",
    bestSeason: "Apr – May, Sep – Oct",
    idealDuration: "3–5 days",
    travelVibe: "Imperial & Elegant",
    insiderTip:
      "Buy a Vienna City Card — it covers all public transport and gives discounts to major museums, saving you significant money.",
    highlights: ["Schönbrunn Palace", "Vienna Opera House", "Belvedere Museum"],
    imageUrl:
      "https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800&q=80",
  },
  {
    id: 40,
    name: "Galapagos Islands, Ecuador",
    country: "Ecuador",
    region: "Americas",
    travelType: "nature",
    budget: "luxury",
    description:
      "The living laboratory that inspired Darwin's theory of evolution — giant tortoises, marine iguanas, blue-footed boobies, and sea lions that have never learned to fear humans.",
    estimatedCost: "$3,500 – $7,000",
    bestSeason: "Jun – Dec",
    idealDuration: "7–10 days",
    travelVibe: "Nature & Scientific",
    insiderTip:
      "Book a liveaboard cruise rather than land-based tours — you will access remote islands that day visitors never reach.",
    highlights: [
      "Giant Tortoises",
      "Snorkeling with Sea Lions",
      "Darwin Research Station",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1610226977124-9fd2755d09f2?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZWN1YWRvcnxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 41,
    name: "Seoul, South Korea",
    country: "South Korea",
    region: "East Asia",
    travelType: "cultural",
    budget: "moderate",
    description:
      "A dynamic city of ancient palaces and futuristic tech, K-pop culture, incredible street food markets, and some of the most innovative cuisine in Asia — all wrapped in ultra-efficient infrastructure.",
    estimatedCost: "$1,500 – $3,000",
    bestSeason: "Apr – Jun, Sep – Nov",
    idealDuration: "5–7 days",
    travelVibe: "Urban & Dynamic",
    insiderTip:
      "Get a T-money card for public transport — Seoul's metro is the cleanest and most efficient in the world and costs almost nothing per ride.",
    highlights: [
      "Gyeongbokgung Palace",
      "Bukchon Hanok Village",
      "Myeongdong Street Food",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1601621915196-2621bfb0cd6e?w=800&q=80",
  },
  {
    id: 42,
    name: "Fiji Islands",
    country: "Fiji",
    region: "Oceania",
    travelType: "relaxing",
    budget: "luxury",
    description:
      "Over 300 islands of pure tropical paradise — crystal lagoons, vibrant coral reefs, traditional Fijian villages, and a culture so warm and welcoming that visitors never want to leave.",
    estimatedCost: "$3,000 – $7,000",
    bestSeason: "May – Oct",
    idealDuration: "7–10 days",
    travelVibe: "Tropical & Relaxing",
    insiderTip:
      "Stay on the Mamanuca or Yasawa islands rather than the main island of Viti Levu for a much more authentic and beautiful experience.",
    highlights: [
      "Yasawa Islands",
      "Coral Coast Diving",
      "Traditional Kava Ceremony",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800&q=80",
  },
  {
    id: 43,
    name: "Medina, Saudi Arabia",
    country: "Saudi Arabia",
    region: "Middle East",
    travelType: "spiritual",
    budget: "moderate",
    description:
      "The second holiest city in Islam, home to the Prophet's Mosque — Al-Masjid an-Nabawi — one of the largest mosques in the world and a place of profound peace and spiritual significance for millions.",
    estimatedCost: "$1,500 – $4,000",
    bestSeason: "Nov – Feb",
    idealDuration: "3–5 days",
    travelVibe: "Spiritual & Sacred",
    insiderTip:
      "Visit Al-Masjid an-Nabawi after Fajr prayer at dawn — the atmosphere at sunrise is deeply peaceful and the crowds are much lighter.",
    highlights: ["Al-Masjid an-Nabawi", "Quba Mosque", "Al-Baqi Cemetery"],
    imageUrl:
      "https://images.unsplash.com/photo-1572358899655-f63ece97bfa5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bWVkaW5hfGVufDB8fDB8fHww",
  },
  {
    id: 44,
    name: "Colombo, Sri Lanka",
    country: "Sri Lanka",
    region: "South Asia",
    travelType: "cultural",
    budget: "budget",
    description:
      "A vibrant island nation of ancient Buddhist temples, misty tea plantations, incredible wildlife, golden beaches, and some of the most flavorful cuisine in all of South Asia.",
    estimatedCost: "$700 – $1,600",
    bestSeason: "Dec – Mar",
    idealDuration: "7–10 days",
    travelVibe: "Cultural & Diverse",
    insiderTip:
      "Hire a tuk-tuk driver for a full day for around $15 — they know hidden temples, local food spots, and scenic routes no guidebook mentions.",
    highlights: [
      "Sigiriya Rock Fortress",
      "Temple of the Tooth",
      "Ella Tea Country",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1566296314736-6eaac1ca0cb9?w=800&q=80",
  },
  {
    id: 45,
    name: "Cairo, Egypt",
    country: "Egypt",
    region: "Africa",
    travelType: "cultural",
    budget: "budget",
    description:
      "Home to the last surviving Wonder of the Ancient World — the Great Pyramid of Giza. Cairo is a city of 4,000 years of history, chaotic energy, world-class museums, and unforgettable street food.",
    estimatedCost: "$700 – $1,500",
    bestSeason: "Oct – Apr",
    idealDuration: "4–6 days",
    travelVibe: "Historic & Ancient",
    insiderTip:
      "Visit the Pyramids of Giza on a Friday morning — it is surprisingly quieter and the golden morning light makes for stunning photographs.",
    highlights: [
      "Pyramids of Giza",
      "Egyptian Museum",
      "Khan el-Khalili Bazaar",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1587975844577-56dfe5d3fca8?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8ZWd5cHR8ZW58MHx8MHx8fDA%3D",
  },
  {
    id: 46,
    name: "Luang Prabang, Laos",
    country: "Laos",
    region: "Southeast Asia",
    travelType: "spiritual",
    budget: "budget",
    description:
      "A UNESCO World Heritage town at the confluence of the Mekong and Nam Khan rivers, where saffron-robed monks collect alms at dawn, ancient temples glow at dusk, and life moves at the gentlest pace.",
    estimatedCost: "$500 – $1,200",
    bestSeason: "Nov – Mar",
    idealDuration: "3–5 days",
    travelVibe: "Peaceful & Spiritual",
    insiderTip:
      "Wake up at 5:30am to witness the Tak Bat alms-giving ceremony — stand respectfully back and never use flash photography.",
    highlights: ["Alms Giving Ceremony", "Kuang Si Waterfalls", "Mount Phousi"],
    imageUrl:
      "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80",
  },
  {
    id: 47,
    name: "Cinque Terre, Italy",
    country: "Italy",
    region: "Europe",
    travelType: "relaxing",
    budget: "moderate",
    description:
      "Five impossibly colorful fishing villages clinging to dramatic cliffs above the Italian Riviera, connected by scenic hiking trails with breathtaking views of the turquoise Mediterranean sea.",
    estimatedCost: "$1,500 – $3,000",
    bestSeason: "May – Sep",
    idealDuration: "3–4 days",
    travelVibe: "Scenic & Relaxing",
    insiderTip:
      "Stay in Manarola or Corniglia — they are the least touristy of the five villages and have the most authentic local atmosphere.",
    highlights: ["Via dell'Amore Path", "Vernazza Village", "Monterosso Beach"],
    imageUrl:
      "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80",
  },
  {
    id: 48,
    name: "Muscat, Oman",
    country: "Oman",
    region: "Middle East",
    travelType: "cultural",
    budget: "moderate",
    description:
      "One of the Arab world's most underrated gems — gleaming white mosques, dramatic desert wadis, pristine beaches, ancient forts, and a culture of extraordinary hospitality and calm.",
    estimatedCost: "$1,200 – $2,500",
    bestSeason: "Oct – Mar",
    idealDuration: "5–7 days",
    travelVibe: "Cultural & Serene",
    insiderTip:
      "Drive the Musandam Peninsula for a day — the fjord-like coastline is one of the most dramatic and least visited landscapes in the entire Middle East.",
    highlights: ["Sultan Qaboos Grand Mosque", "Mutrah Souq", "Wadi Shab"],
    imageUrl:
      "https://images.unsplash.com/photo-1599743777555-e362a2feab39?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8b21hbnxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 49,
    name: "Buenos Aires, Argentina",
    country: "Argentina",
    region: "Americas",
    travelType: "cultural",
    budget: "moderate",
    description:
      "The Paris of South America — a city of tango music in cobblestone alleys, world-class steakhouses, European architecture, passionate football culture, and an electric nightlife that starts after midnight.",
    estimatedCost: "$1,200 – $2,500",
    bestSeason: "Sep – Nov, Mar – May",
    idealDuration: "5–7 days",
    travelVibe: "Vibrant & Passionate",
    insiderTip:
      "Book a table at a parrilla (steakhouse) for 9:30pm — that is when locals eat and the atmosphere is completely different from early tourist sittings.",
    highlights: [
      "La Boca Neighborhood",
      "Recoleta Cemetery",
      "San Telmo Market",
    ],
    imageUrl:
      "https://plus.unsplash.com/premium_photo-1697729979889-31ec7ecf6f06?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8YXJnZW50aW5hfGVufDB8fDB8fHww",
  },
  {
    id: 50,
    name: "Chiang Mai, Thailand",
    country: "Thailand",
    region: "Southeast Asia",
    travelType: "cultural",
    budget: "budget",
    description:
      "Northern Thailand's cultural capital — ancient walled temples, night markets selling handcrafted goods, elephant sanctuaries in the jungle, and cooking classes teaching authentic Thai cuisine.",
    estimatedCost: "$500 – $1,200",
    bestSeason: "Nov – Feb",
    idealDuration: "5–7 days",
    travelVibe: "Cultural & Relaxed",
    insiderTip:
      "Visit Doi Suthep temple at sunrise before 7am — you will have the mountain temple almost entirely to yourself with mist rolling through the valleys below.",
    highlights: [
      "Doi Suthep Temple",
      "Sunday Night Market",
      "Ethical Elephant Sanctuary",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80",
  },
  {
    id: 51,
    name: "Dubrovnik, Croatia",
    country: "Croatia",
    region: "Europe",
    travelType: "relaxing",
    budget: "comfort",
    description:
      "The Pearl of the Adriatic — a perfectly preserved medieval walled city on a dramatic limestone peninsula, with crystal-clear waters below and Game of Thrones filming locations around every corner.",
    estimatedCost: "$2,000 – $3,500",
    bestSeason: "May – Jun, Sep – Oct",
    idealDuration: "3–5 days",
    travelVibe: "Historic & Scenic",
    insiderTip:
      "Walk the city walls at 8am before the cruise ship crowds arrive — the views over the old town and Adriatic at that hour are absolutely magical.",
    highlights: ["City Walls Walk", "Old Town", "Lokrum Island"],
    imageUrl:
      "https://images.unsplash.com/photo-1555990793-da11153b2473?w=800&q=80",
  },
  {
    id: 52,
    name: "Tbilisi, Georgia",
    country: "Georgia",
    region: "Europe",
    travelType: "cultural",
    budget: "budget",
    description:
      "One of Europe's most underrated capitals — a fascinating mix of Persian, Russian, and Caucasian cultures, ancient churches, sulfuric bathhouses, natural wine culture, and incredibly warm hospitality.",
    estimatedCost: "$600 – $1,400",
    bestSeason: "Apr – Jun, Sep – Oct",
    idealDuration: "4–5 days",
    travelVibe: "Unique & Affordable",
    insiderTip:
      "Take a cable car to Narikala Fortress at sunset — the panoramic view over the old town with the Kura River winding below is one of the best in all of Europe.",
    highlights: ["Narikala Fortress", "Sulphur Baths", "Rustaveli Avenue"],
    imageUrl:
      "https://images.unsplash.com/photo-1565008576549-57569a49371d?w=800&q=80",
  },
  {
    id: 53,
    name: "Kathmandu, Nepal",
    country: "Nepal",
    region: "South Asia",
    travelType: "spiritual",
    budget: "budget",
    description:
      "The gateway to the Himalayas — a city of ancient Hindu temples, Buddhist stupas, the smell of incense, and the starting point for the world's greatest mountain treks including Everest Base Camp.",
    estimatedCost: "$500 – $1,200",
    bestSeason: "Oct – Nov, Mar – Apr",
    idealDuration: "3–5 days",
    travelVibe: "Spiritual & Adventure",
    insiderTip:
      "Fly into Lukla rather than trekking from Kathmandu if time is limited — it saves 7 days and puts you straight into the stunning Khumbu region.",
    highlights: [
      "Swayambhunath Stupa",
      "Pashupatinath Temple",
      "Everest Base Camp Trek",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80",
  },
  {
    id: 54,
    name: "Cartagena, Colombia",
    country: "Colombia",
    region: "Americas",
    travelType: "romantic",
    budget: "moderate",
    description:
      "A fairy-tale Caribbean city of candy-colored colonial buildings, bougainvillea-draped balconies, ancient fortresses, white-sand islands, and some of the most vibrant nightlife in South America.",
    estimatedCost: "$1,000 – $2,200",
    bestSeason: "Dec – Apr",
    idealDuration: "4–5 days",
    travelVibe: "Romantic & Colorful",
    insiderTip:
      "Stay inside the walled city in a boutique hotel — the experience of waking up to those colorful streets and sounds is completely different from staying outside the walls.",
    highlights: ["Walled Old City", "Rosario Islands", "Castle San Felipe"],
    imageUrl:
      "https://plus.unsplash.com/premium_photo-1697730015412-75b8223ae1fc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Y29sb21iaWF8ZW58MHx8MHx8fDA%3D",
  },
  {
    id: 55,
    name: "Melbourne, Australia",
    country: "Australia",
    region: "Oceania",
    travelType: "cultural",
    budget: "comfort",
    description:
      "Australia's cultural capital — world-class coffee, vibrant street art laneways, incredible food markets, rooftop bars, a thriving arts scene, and the most passionate sports culture in the southern hemisphere.",
    estimatedCost: "$2,000 – $4,000",
    bestSeason: "Sep – Nov, Mar – May",
    idealDuration: "4–6 days",
    travelVibe: "Urban & Creative",
    insiderTip:
      "Explore Hosier Lane and AC/DC Lane in the morning light — the street art changes constantly and looks stunning in the early golden hour light.",
    highlights: [
      "Federation Square",
      "Queen Victoria Market",
      "Great Ocean Road",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1514395462725-fb4566210144?w=800&q=80",
  },
  {
    id: 56,
    name: "Marrakech Sahara, Morocco",
    country: "Morocco",
    region: "Africa",
    travelType: "adventure",
    budget: "moderate",
    description:
      "Journey from the vibrant chaos of Marrakech into the vast silence of the Sahara Desert — riding camels over golden dunes, sleeping under a billion stars in a desert camp, and watching the most dramatic sunrises on earth.",
    estimatedCost: "$1,000 – $2,500",
    bestSeason: "Oct – Apr",
    idealDuration: "5–7 days",
    travelVibe: "Adventure & Epic",
    insiderTip:
      "Book a private desert camp rather than a group tour — the difference in experience and tranquility under the Sahara stars is worth every extra dirham.",
    highlights: [
      "Erg Chebbi Sand Dunes",
      "Camel Trekking",
      "Desert Stargazing",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80",
  },
  {
    id: 57,
    name: "Singapore",
    country: "Singapore",
    region: "Southeast Asia",
    travelType: "luxury",
    budget: "luxury",
    description:
      "Asia's most polished city-state — gleaming supertrees in Gardens by the Bay, a world-class hawker food culture, Michelin-starred restaurants, rooftop infinity pools, and remarkable multicultural harmony.",
    estimatedCost: "$2,500 – $5,000",
    bestSeason: "Feb – Apr",
    idealDuration: "3–5 days",
    travelVibe: "Luxury & Modern",
    insiderTip:
      "Eat at hawker centres like Maxwell Food Centre rather than restaurants — Singapore's street food is arguably the best in Asia and costs under $5 per dish.",
    highlights: [
      "Gardens by the Bay",
      "Marina Bay Sands",
      "Hawker Centre Food Tour",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80",
  },
  {
    id: 58,
    name: "Bruges, Belgium",
    country: "Belgium",
    region: "Europe",
    travelType: "romantic",
    budget: "moderate",
    description:
      "A perfectly preserved medieval city of chocolate shops, canal boats, Gothic architecture, and the world's finest Belgian beer. Bruges looks like a fairy tale and feels even more magical in person.",
    estimatedCost: "$1,200 – $2,500",
    bestSeason: "Apr – Sep",
    idealDuration: "2–3 days",
    travelVibe: "Romantic & Fairytale",
    insiderTip:
      "Climb the Belfry tower early morning for the best view over the medieval rooftops — and visit the chocolate shops before noon for the freshest pralines.",
    highlights: ["Canal Boat Tour", "Belfry Tower", "Bruges Chocolate Tour"],
    imageUrl:
      "https://images.unsplash.com/photo-1491557345352-5929e343eb89?w=800&q=80",
  },
  {
    id: 59,
    name: "Socotra Island, Yemen",
    country: "Yemen",
    region: "Middle East",
    travelType: "nature",
    budget: "moderate",
    description:
      "The Galapagos of the Indian Ocean — a remote UNESCO island where 37% of plant species exist nowhere else on earth, including the alien-looking Dragon Blood Trees that cover the plateau.",
    estimatedCost: "$1,500 – $3,000",
    bestSeason: "Oct – May",
    idealDuration: "7–10 days",
    travelVibe: "Wild & Otherworldly",
    insiderTip:
      "Travel with a reputable local agency — they handle all logistics on this remote island and their local knowledge is absolutely essential for the experience.",
    highlights: ["Dragon Blood Trees", "Detwah Lagoon", "Diksam Plateau"],
    imageUrl:
      "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&q=80",
  },
  {
    id: 60,
    name: "Vancouver, Canada",
    country: "Canada",
    region: "Americas",
    travelType: "nature",
    budget: "comfort",
    description:
      "A stunning Pacific Coast city where snow-capped mountains plunge into the ocean, ancient rainforests sit minutes from downtown, and world-class skiing, hiking, and kayaking are all within easy reach.",
    estimatedCost: "$2,000 – $4,000",
    bestSeason: "Jun – Sep",
    idealDuration: "4–6 days",
    travelVibe: "Nature & Urban",
    insiderTip:
      "Cycle the Stanley Park seawall early in the morning — the views of the mountains reflecting in the harbor with downtown behind you are absolutely world-class.",
    highlights: [
      "Stanley Park",
      "Whistler Day Trip",
      "Granville Island Market",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1559511260-66a654ae982a?w=800&q=80",
  },
  {
    id: 61,
    name: "Taipei, Taiwan",
    country: "Taiwan",
    region: "East Asia",
    travelType: "cultural",
    budget: "budget",
    description:
      "A compact, welcoming city of incredible night markets, bubble tea culture, stunning mountain temples, excellent museums, and some of the friendliest and most helpful people in all of Asia.",
    estimatedCost: "$800 – $1,800",
    bestSeason: "Sep – Nov, Mar – Apr",
    idealDuration: "4–5 days",
    travelVibe: "Affordable & Friendly",
    insiderTip:
      "The EasyCard works on all MRT, buses, and YouBike rentals — buy one at the airport on arrival and it makes getting around extremely easy.",
    highlights: ["Taipei 101", "Shilin Night Market", "Jiufen Old Street"],
    imageUrl:
      "https://images.unsplash.com/photo-1470004914212-05527e49370b?w=800&q=80",
  },
  {
    id: 62,
    name: "Lagos, Nigeria",
    country: "Nigeria",
    region: "Africa",
    travelType: "cultural",
    budget: "moderate",
    description:
      "Africa's largest city and most energetic megacity — a pulsating hub of Afrobeats music, incredible jollof rice, Lagos Island beaches, thriving art scenes, and an unstoppable entrepreneurial spirit.",
    estimatedCost: "$1,000 – $2,500",
    bestSeason: "Nov – Feb",
    idealDuration: "4–6 days",
    travelVibe: "Vibrant & Energetic",
    insiderTip:
      "Visit Nike Art Gallery in Lekki — it is the largest art gallery in West Africa and the owner Nike Davies-Okundaye is often there to share the stories behind the works.",
    highlights: ["Tarkwa Bay Beach", "Nike Art Gallery", "Balogun Market"],
    imageUrl:
      "https://images.unsplash.com/photo-1648023200358-9dc050df521d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fG5pZ2VyaWF8ZW58MHx8MHx8fDA%3D",
  },
  {
    id: 63,
    name: "Seville, Spain",
    country: "Spain",
    region: "Europe",
    travelType: "cultural",
    budget: "moderate",
    description:
      "The soul of Andalusia — flamenco dancing in candlelit tablaos, orange-tree-lined streets, the magnificent Alcázar palace, cathedral spires, and tapas culture at its very finest.",
    estimatedCost: "$1,200 – $2,500",
    bestSeason: "Mar – May, Sep – Oct",
    idealDuration: "3–4 days",
    travelVibe: "Passionate & Cultural",
    insiderTip:
      "Book a flamenco show at Tablao El Arenal rather than tourist shows — the performers are professional artists and the intimate setting makes it genuinely moving.",
    highlights: ["Real Alcázar", "Seville Cathedral", "Flamenco Show"],
    imageUrl:
      "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800&q=80",
  },
  {
    id: 64,
    name: "Paro, Bhutan",
    country: "Bhutan",
    region: "South Asia",
    travelType: "adventure",
    budget: "luxury",
    description:
      "Home to the iconic Tiger's Nest Monastery — one of the most spectacular and sacred sites in Asia, perched impossibly on a 900-meter cliff above the Paro Valley floor.",
    estimatedCost: "$3,000 – $6,000",
    bestSeason: "Mar – May, Sep – Nov",
    idealDuration: "5–7 days",
    travelVibe: "Spiritual & Adventurous",
    insiderTip:
      "Start the Tiger's Nest hike at 7am to avoid crowds and catch the monastery in morning mist — bring a poncho as weather changes rapidly at altitude.",
    highlights: ["Tiger's Nest Monastery", "Paro Dzong", "Drukgyel Dzong"],
    imageUrl:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
  },
  {
    id: 65,
    name: "Mariana Trench Area, Micronesia",
    country: "Micronesia",
    region: "Oceania",
    travelType: "adventure",
    budget: "luxury",
    description:
      "The remote islands of Micronesia offer some of the world's finest wreck diving, pristine coral reefs, WWII history underwater, and isolated island life far from any tourist trail.",
    estimatedCost: "$3,000 – $6,000",
    bestSeason: "Nov – May",
    idealDuration: "7–10 days",
    travelVibe: "Adventure & Remote",
    insiderTip:
      "Chuuk Lagoon has the largest collection of WWII shipwrecks in the world — even beginner divers can explore some of the shallow wrecks with a guide.",
    highlights: ["WWII Wreck Diving", "Pohnpei Ruins", "Remote Island Beaches"],
    imageUrl:
      "https://images.unsplash.com/photo-1559511260-66a654ae982a?w=800&q=80",
  },
  {
    id: 66,
    name: "Addis Ababa, Ethiopia",
    country: "Ethiopia",
    region: "Africa",
    travelType: "cultural",
    budget: "budget",
    description:
      "The birthplace of coffee, ancient rock-hewn churches, the legendary Simien Mountains, and Lucy — the 3.2 million year old fossil that changed our understanding of human evolution.",
    estimatedCost: "$700 – $1,500",
    bestSeason: "Oct – Jan",
    idealDuration: "5–7 days",
    travelVibe: "Historic & Authentic",
    insiderTip:
      "Attend a traditional Ethiopian coffee ceremony in a local home rather than a café — the three rounds of coffee over an hour is a deeply cultural experience.",
    highlights: [
      "Lalibela Rock Churches",
      "Simien Mountains",
      "National Museum of Ethiopia",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1634029878815-1bb307302471?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8ZXRoaW9waWF8ZW58MHx8MHx8fDA%3D",
  },
  {
    id: 67,
    name: "Sydney, Australia",
    country: "Australia",
    region: "Oceania",
    travelType: "relaxing",
    budget: "comfort",
    description:
      "One of the world's most beautiful harbor cities — the iconic Opera House, Bondi Beach surf culture, Harbour Bridge walks, vibrant café culture, and stunning coastal walks in every direction.",
    estimatedCost: "$2,500 – $5,000",
    bestSeason: "Sep – Nov, Mar – May",
    idealDuration: "5–7 days",
    travelVibe: "Coastal & Vibrant",
    insiderTip:
      "Walk from Bondi to Coogee along the coastal cliff path in the morning — it is completely free, one of the most beautiful urban walks in the world, and takes about 2 hours.",
    highlights: ["Sydney Opera House", "Bondi Beach", "Harbour Bridge Climb"],
    imageUrl:
      "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&q=80",
  },
  {
    id: 68,
    name: "Kotor, Montenegro",
    country: "Montenegro",
    region: "Europe",
    travelType: "romantic",
    budget: "budget",
    description:
      "A hidden gem of the Adriatic — a perfectly preserved medieval walled city nestled between dramatic mountains and a stunning bay, with Venetian architecture, cat-filled streets, and zero crowds.",
    estimatedCost: "$700 – $1,500",
    bestSeason: "May – Jun, Sep – Oct",
    idealDuration: "2–4 days",
    travelVibe: "Romantic & Hidden Gem",
    insiderTip:
      "Climb the fortress walls at sunset for the most spectacular view over the Bay of Kotor — the hike takes about 45 minutes and the panorama at the top is breathtaking.",
    highlights: ["Old Town Walls", "Bay of Kotor", "Our Lady of the Rocks"],
    imageUrl:
      "https://images.unsplash.com/photo-1555990793-da11153b2473?w=800&q=80",
  },
  {
    id: 69,
    name: "Oaxaca, Mexico",
    country: "Mexico",
    region: "Americas",
    travelType: "cultural",
    budget: "budget",
    description:
      "Mexico's culinary and cultural heartland — mezcal distilleries, ancient Zapotec ruins, vibrant Day of the Dead celebrations, incredible mole dishes, and colorful markets overflowing with artisan crafts.",
    estimatedCost: "$700 – $1,600",
    bestSeason: "Oct – May",
    idealDuration: "4–6 days",
    travelVibe: "Cultural & Culinary",
    insiderTip:
      "Visit Mercado Benito Juárez for breakfast — order a tlayuda with black beans, tasajo, and quesillo cheese for the most authentic Oaxacan meal you will ever have.",
    highlights: [
      "Monte Albán Ruins",
      "Day of the Dead Festival",
      "Mezcal Distillery Tour",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1518638150340-f706e86654de?w=800&q=80",
  },
  {
    id: 70,
    name: "Tallinn, Estonia",
    country: "Estonia",
    region: "Europe",
    travelType: "cultural",
    budget: "budget",
    description:
      "One of Europe's best-preserved medieval cities — cobblestone streets, Gothic town hall, ancient towers, a thriving digital culture, and long summer evenings with light until midnight.",
    estimatedCost: "$700 – $1,500",
    bestSeason: "May – Aug",
    idealDuration: "2–3 days",
    travelVibe: "Medieval & Unique",
    insiderTip:
      "Walk the old town walls in the evening when the day crowds have left — the medieval towers lit up against the darkening sky make for magical photography.",
    highlights: ["Old Town", "Toompea Castle", "Telliskivi Creative City"],
    imageUrl:
      "https://images.unsplash.com/photo-1709862366377-54b16f3e51f9?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZXN0b25pYXxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 71,
    name: "Luxor, Egypt",
    country: "Egypt",
    region: "Africa",
    travelType: "cultural",
    budget: "budget",
    description:
      "The world's greatest open-air museum — the Valley of the Kings, Karnak Temple, Luxor Temple, and the tombs of pharaohs are all within a short distance in what was once ancient Thebes.",
    estimatedCost: "$600 – $1,400",
    bestSeason: "Oct – Apr",
    idealDuration: "3–4 days",
    travelVibe: "Ancient & Historic",
    insiderTip:
      "Hire a private guide for the Valley of the Kings — they know which tombs are least crowded and can explain the hieroglyphic stories in ways that bring ancient Egypt to life.",
    highlights: [
      "Valley of the Kings",
      "Karnak Temple",
      "Luxor Temple at Night",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1629468855534-450d7c4c5f72?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bHV4b3IlMjBlZ3lwdHxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 72,
    name: "Kochi, India",
    country: "India",
    region: "South Asia",
    travelType: "cultural",
    budget: "budget",
    description:
      "Kerala's most charming city — a spice-scented port with Chinese fishing nets, Dutch palaces, synagogues, Kathakali dance performances, and the gateway to Kerala's legendary backwaters.",
    estimatedCost: "$500 – $1,200",
    bestSeason: "Oct – Mar",
    idealDuration: "3–5 days",
    travelVibe: "Cultural & Serene",
    insiderTip:
      "Take a houseboat overnight through the Kerala backwaters from Alleppey rather than Kochi — the experience of drifting through village life on still waters is utterly peaceful.",
    highlights: [
      "Kerala Backwaters",
      "Chinese Fishing Nets",
      "Kathakali Performance",
    ],
    imageUrl:
      "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&q=80",
  },
  {
    id: 73,
    name: "Tulum, Mexico",
    country: "Mexico",
    region: "Americas",
    travelType: "relaxing",
    budget: "moderate",
    description:
      "A bohemian Caribbean paradise of white-sand beaches, turquoise cenotes, ancient Mayan cliff-top ruins, eco-chic jungle hotels, and a wellness culture that has taken the travel world by storm.",
    estimatedCost: "$1,200 – $2,800",
    bestSeason: "Nov – Apr",
    idealDuration: "5–7 days",
    travelVibe: "Bohemian & Relaxing",
    insiderTip:
      "Rent a bicycle to get around — the main hotel zone is 3km long and cycling between cenotes, ruins, and beaches is far cheaper and more fun than taxis.",
    highlights: ["Tulum Ruins", "Gran Cenote", "Sian Ka'an Biosphere"],
    imageUrl:
      "https://images.unsplash.com/photo-1516815231560-8f41ec531527?w=800&q=80",
  },
  {
    id: 74,
    name: "Mozambique",
    country: "Mozambique",
    region: "Africa",
    travelType: "adventure",
    budget: "moderate",
    description:
      "East Africa's most undiscovered paradise — pristine dhow-sailing coastlines, world-class diving with manta rays, deserted archipelago islands, Afro-Portuguese colonial culture, and extraordinary seafood.",
    estimatedCost: "$1,500 – $3,500",
    bestSeason: "May – Nov",
    idealDuration: "7–10 days",
    travelVibe: "Wild & Undiscovered",
    insiderTip:
      "Book a sailing dhow trip from Vilanculos to the Bazaruto Archipelago — the islands have some of the clearest water and most vibrant coral reefs left in the Indian Ocean.",
    highlights: [
      "Bazaruto Archipelago",
      "Quirimbas Islands",
      "Manta Ray Diving",
    ],
    imageUrl:
      "https://plus.unsplash.com/premium_photo-1671358446946-8bd43ba08a6a?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bW96YW1iaXF1ZXxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 75,
    name: "Sarajevo, Bosnia",
    country: "Bosnia & Herzegovina",
    region: "Europe",
    travelType: "cultural",
    budget: "budget",
    description:
      "Europe's most underrated city — a place where Ottoman mosques, Austro-Hungarian architecture, and Yugoslav history coexist on the same street, with the world's best cevapi and extraordinary human resilience.",
    estimatedCost: "$600 – $1,300",
    bestSeason: "Apr – Oct",
    idealDuration: "3–4 days",
    travelVibe: "Historic & Authentic",
    insiderTip:
      "Walk across Latin Bridge where Archduke Franz Ferdinand was assassinated — then eat at Inat Kuća restaurant opposite for traditional Bosnian food in a historic setting.",
    highlights: ["Baščaršija Bazaar", "Latin Bridge", "Tunnel of Hope Museum"],
    imageUrl:
      "https://images.unsplash.com/photo-1716968921500-6bce26915c37?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Ym9zbmlhfGVufDB8fDB8fHww",
  },
  {
    id: 76,
    name: "Mendoza, Argentina",
    country: "Argentina",
    region: "Americas",
    travelType: "relaxing",
    budget: "moderate",
    description:
      "The wine capital of South America — rows of Malbec vines stretching to Andean snow-caps, world-class bodegas, cycling between vineyards, gourmet restaurants, and the most spectacular mountain scenery.",
    estimatedCost: "$1,000 – $2,200",
    bestSeason: "Mar – May, Sep – Nov",
    idealDuration: "3–5 days",
    travelVibe: "Wine & Relaxation",
    insiderTip:
      "Rent a bicycle and spend a full day cycling the Luján de Cuyo wine route — most bodegas accept walk-ins for tastings and the mountain views from the vineyards are spectacular.",
    highlights: [
      "Malbec Wine Tasting",
      "Aconcagua Views",
      "Luján de Cuyo Wineries",
    ],
    imageUrl:
      "https://plus.unsplash.com/premium_photo-1697729859616-de0cceead7d8?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bWVuZG96YSUyMGFyZ2VudGluYXxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 77,
    name: "Taipei Night Markets",
    country: "Taiwan",
    region: "East Asia",
    travelType: "foodie",
    budget: "budget",
    description:
      "Taiwan's legendary night market culture — Shilin, Raohe, and Ningxia markets overflowing with stinky tofu, oyster omelettes, bubble tea, scallion pancakes, and hundreds of incredible street food stalls.",
    estimatedCost: "$600 – $1,400",
    bestSeason: "Sep – Nov",
    idealDuration: "3–4 days",
    travelVibe: "Foodie & Fun",
    insiderTip:
      "Go to Ningxia Night Market rather than Shilin — it is smaller, more authentic, and favored by locals rather than tourists, with equally incredible food.",
    highlights: ["Shilin Night Market", "Raohe Street Market", "Din Tai Fung"],
    imageUrl:
      "https://images.unsplash.com/photo-1470004914212-05527e49370b?w=800&q=80",
  },
  {
    id: 78,
    name: "Bandar Seri Begawan, Brunei",
    country: "Brunei",
    region: "Southeast Asia",
    travelType: "cultural",
    budget: "moderate",
    description:
      "One of Asia's smallest and most peaceful nations — the stunning Omar Ali Saifuddien Mosque, the world's largest water village Kampong Ayer, and a pristine rainforest covering 70% of the country.",
    estimatedCost: "$1,000 – $2,000",
    bestSeason: "Dec – Feb",
    idealDuration: "2–3 days",
    travelVibe: "Peaceful & Unique",
    insiderTip:
      "Take a water taxi to Kampong Ayer water village and walk through the elevated boardwalks — over 30,000 people live here and it is one of Asia's most extraordinary communities.",
    highlights: [
      "Omar Ali Saifuddien Mosque",
      "Kampong Ayer Water Village",
      "Ulu Temburong National Park",
    ],
    imageUrl:
      "https://plus.unsplash.com/premium_photo-1673288455625-fa00f5ff831f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8YnJ1bmVpfGVufDB8fDB8fHww",
  },
  {
    id: 79,
    name: "Almaty, Kazakhstan",
    country: "Kazakhstan",
    region: "Middle East",
    travelType: "adventure",
    budget: "moderate",
    description:
      "Central Asia's most cosmopolitan city nestled below the Tian Shan mountains — world-class skiing in winter, stunning alpine lakes like Big Almaty Lake, Soviet architecture, and a buzzing café culture.",
    estimatedCost: "$1,000 – $2,200",
    bestSeason: "May – Sep, Dec – Feb",
    idealDuration: "4–5 days",
    travelVibe: "Adventure & Urban",
    insiderTip:
      "Take the Kok-Tobe cable car at sunset and stay for dinner at the summit restaurant — the panoramic view of Almaty with the snow-capped Tian Shan behind it is extraordinary.",
    highlights: ["Big Almaty Lake", "Shymbulak Ski Resort", "Green Bazaar"],
    imageUrl:
      "https://plus.unsplash.com/premium_photo-1697730150003-26a1d469adb4?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8a2F6YWtoc3RhbnxlbnwwfHwwfHx8MA%3D%3D",
  },
];

// ── CONTROLLER ──
const getRecommendations = (req, res) => {
  try {
    const { travelType, budget, region } = req.query;

    let results = [...destinations];

    if (travelType) {
      results = results.filter(
        (d) => d.travelType.toLowerCase() === travelType.toLowerCase(),
      );
    }

    if (budget) {
      results = results.filter(
        (d) => d.budget.toLowerCase() === budget.toLowerCase(),
      );
    }

    if (region) {
      results = results.filter(
        (d) => d.region.toLowerCase() === region.toLowerCase(),
      );
    }

    // If filters matched nothing, return everything
    if (results.length === 0) {
      results = destinations;
    }

    res.status(200).json({
      success: true,
      count: results.length,
      destinations: results,
    });
  } catch (err) {
    console.error("Controller error:", err.message);
    res.status(500).json({
      success: false,
      error: "Failed to fetch recommendations",
    });
  }
};

module.exports = { getRecommendations };
